Document: la-storia-in-giallo
Title: Debian la-storia-in-giallo Manual
Author: <insert document author here>
Abstract: This manual describes what la-storia-in-giallo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/la-storia-in-giallo/la-storia-in-giallo.sgml.gz

Format: postscript
Files: /usr/share/doc/la-storia-in-giallo/la-storia-in-giallo.ps.gz

Format: text
Files: /usr/share/doc/la-storia-in-giallo/la-storia-in-giallo.text.gz

Format: HTML
Index: /usr/share/doc/la-storia-in-giallo/html/index.html
Files: /usr/share/doc/la-storia-in-giallo/html/*.html
